name: tests

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Testing
      run: |
        python actions_test.py
